version: '1'
services:
  profile-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "profile_service"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REACT_APP_API_URL=host.docker.internal:443
      - DB_HOST=host.docker.internal:27017
      - DB_USER=root
      - DB_PASSWORD=example
      - SECRET_KEY=ilovesecretkeys
    ports:
      - 443:3000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodb_data_container:
